# Generated by Django 5.1.2 on 2024-11-10 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('user', '0002_city_region_remove_address_district_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/profile.jpeg', null=True, upload_to='company/profile_images/'),
        ),
    ]
