# Generated by Django 5.1.2 on 2024-12-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companyprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='image',
            field=models.ImageField(blank=True, default='company/profile_images/information_items_property_13610.jpg', null=True, upload_to='company/profile_images/'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='video',
            field=models.FileField(blank=True, default='company/videos/venue.mp4', null=True, upload_to='company/videos/'),
        ),
    ]
