# Generated by Django 5.1.2 on 2024-12-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companyprofile_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyorderacceptance',
            name='person_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
